<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>_16th__july_assignment</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\NewFolder1\" />
  </ItemGroup>

</Project>
